language: ruby
rvm:
  - 2.0.0
before_install:
  - git submodule update --init --recursive
  - sudo apt-get install nmap
  - sudo apt-get install wget
  - sudo apt-get install libcurl4-openssl-dev
  - 'cd vendor && wget https://github.com/iSECPartners/sslyze/releases/download/release-0.9/sslyze-0_9-linux64.zip && unzip sslyze-0_9-linux64.zip && cd ..'
  - export SSLYZE_PATH="$TRAVIS_BUILD_DIR/vendor/sslyze-0_9-linux64/sslyze.py"
before_script:
  - ./set_token.sh
  - bundle exec rake db:migrate
  - bundle exec rails s -d
script: 
  - bundle exec rake secure_pipeline:network_attack
  - bundle exec rake secure_pipeline:ssl_attack
